CREATE OR REPLACE VIEW CUSTOMER360.ANALYTICS.CUSTOMER_ACTIVITY AS
SELECT CUSTOMER_ID, COUNT(*) EVENT_COUNT, MAX(OCCURRED_AT) LAST_ACTIVITY_AT
FROM CUSTOMER360.RAW.CUSTOMER_EVENTS GROUP BY CUSTOMER_ID;
