-- Analytics star schema. Foreign-key constraints are informational in Snowflake.
CREATE TABLE IF NOT EXISTS CUSTOMER360.ANALYTICS.DIM_CUSTOMER (
  CUSTOMER_KEY NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  CUSTOMER_ID STRING NOT NULL,
  EXTERNAL_ID STRING,
  FULL_NAME STRING,
  EMAIL STRING,
  PHONE STRING,
  DATE_OF_BIRTH DATE,
  GENDER STRING,
  CITY STRING,
  STATE_PROVINCE STRING,
  POSTAL_CODE STRING,
  COUNTRY_CODE STRING,
  CUSTOMER_STATUS STRING,
  CUSTOMER_SEGMENT STRING,
  SOURCE_SYSTEM STRING,
  MARKETING_CONSENT BOOLEAN,
  EFFECTIVE_FROM TIMESTAMP_TZ NOT NULL,
  EFFECTIVE_TO TIMESTAMP_TZ,
  IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
  RECORD_HASH STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_KEY) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS CUSTOMER360.ANALYTICS.FACT_TRANSACTION (
  TRANSACTION_KEY NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  TRANSACTION_ID STRING NOT NULL,
  CUSTOMER_KEY NUMBER(38,0) NOT NULL,
  TRANSACTION_TYPE STRING,
  STATUS STRING,
  AMOUNT NUMBER(18,2) NOT NULL,
  TAX_AMOUNT NUMBER(18,2) NOT NULL DEFAULT 0,
  DISCOUNT_AMOUNT NUMBER(18,2) NOT NULL DEFAULT 0,
  NET_AMOUNT NUMBER(18,2) NOT NULL,
  CURRENCY STRING,
  PAYMENT_METHOD STRING,
  CHANNEL STRING,
  PRODUCT_ID STRING,
  QUANTITY NUMBER(10,0),
  TRANSACTED_AT TIMESTAMP_TZ NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FACT_TRANSACTION PRIMARY KEY (TRANSACTION_KEY) NOT ENFORCED,
  CONSTRAINT FK_TRANSACTION_CUSTOMER FOREIGN KEY (CUSTOMER_KEY)
    REFERENCES CUSTOMER360.ANALYTICS.DIM_CUSTOMER(CUSTOMER_KEY) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS CUSTOMER360.ANALYTICS.FACT_SUPPORT (
  SUPPORT_KEY NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  SUPPORT_ID STRING NOT NULL,
  CUSTOMER_KEY NUMBER(38,0) NOT NULL,
  TICKET_NUMBER STRING,
  CHANNEL STRING,
  CATEGORY STRING,
  PRIORITY STRING,
  STATUS STRING,
  SUBJECT STRING,
  SATISFACTION_SCORE NUMBER(1,0),
  OPENED_AT TIMESTAMP_TZ NOT NULL,
  FIRST_RESPONSE_AT TIMESTAMP_TZ,
  RESOLVED_AT TIMESTAMP_TZ,
  FIRST_RESPONSE_MINUTES NUMBER(12,2),
  RESOLUTION_MINUTES NUMBER(12,2),
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FACT_SUPPORT PRIMARY KEY (SUPPORT_KEY) NOT ENFORCED,
  CONSTRAINT FK_SUPPORT_CUSTOMER FOREIGN KEY (CUSTOMER_KEY)
    REFERENCES CUSTOMER360.ANALYTICS.DIM_CUSTOMER(CUSTOMER_KEY) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS CUSTOMER360.ANALYTICS.FACT_MARKETING (
  MARKETING_KEY NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  MARKETING_ID STRING NOT NULL,
  CUSTOMER_KEY NUMBER(38,0) NOT NULL,
  CAMPAIGN_ID STRING NOT NULL,
  CAMPAIGN_NAME STRING,
  CHANNEL STRING,
  INTERACTION_TYPE STRING,
  CONVERSION_VALUE NUMBER(18,2),
  OCCURRED_AT TIMESTAMP_TZ NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FACT_MARKETING PRIMARY KEY (MARKETING_KEY) NOT ENFORCED,
  CONSTRAINT FK_MARKETING_CUSTOMER FOREIGN KEY (CUSTOMER_KEY)
    REFERENCES CUSTOMER360.ANALYTICS.DIM_CUSTOMER(CUSTOMER_KEY) NOT ENFORCED
);

CREATE OR REPLACE VIEW CUSTOMER360.ANALYTICS.CUSTOMER_ACTIVITY AS
SELECT
  C.CUSTOMER_KEY,
  C.CUSTOMER_ID,
  COALESCE(T.TRANSACTION_COUNT, 0) AS TRANSACTION_COUNT,
  COALESCE(T.LIFETIME_VALUE, 0) AS LIFETIME_VALUE,
  T.LAST_TRANSACTION_AT,
  COALESCE(S.SUPPORT_CASE_COUNT, 0) AS SUPPORT_CASE_COUNT,
  S.LAST_SUPPORT_AT,
  COALESCE(M.MARKETING_ENGAGEMENT_COUNT, 0) AS MARKETING_ENGAGEMENT_COUNT,
  M.LAST_MARKETING_AT
FROM CUSTOMER360.ANALYTICS.DIM_CUSTOMER C
LEFT JOIN (
  SELECT CUSTOMER_KEY, COUNT(*) AS TRANSACTION_COUNT,
         SUM(NET_AMOUNT) AS LIFETIME_VALUE, MAX(TRANSACTED_AT) AS LAST_TRANSACTION_AT
  FROM CUSTOMER360.ANALYTICS.FACT_TRANSACTION GROUP BY CUSTOMER_KEY
) T ON C.CUSTOMER_KEY = T.CUSTOMER_KEY
LEFT JOIN (
  SELECT CUSTOMER_KEY, COUNT(*) AS SUPPORT_CASE_COUNT, MAX(OPENED_AT) AS LAST_SUPPORT_AT
  FROM CUSTOMER360.ANALYTICS.FACT_SUPPORT GROUP BY CUSTOMER_KEY
) S ON C.CUSTOMER_KEY = S.CUSTOMER_KEY
LEFT JOIN (
  SELECT CUSTOMER_KEY, COUNT(*) AS MARKETING_ENGAGEMENT_COUNT, MAX(OCCURRED_AT) AS LAST_MARKETING_AT
  FROM CUSTOMER360.ANALYTICS.FACT_MARKETING GROUP BY CUSTOMER_KEY
) M ON C.CUSTOMER_KEY = M.CUSTOMER_KEY
WHERE C.IS_CURRENT = TRUE;
