-- Immutable, source-aligned landing tables. VARIANT preserves the original record.
CREATE TABLE IF NOT EXISTS CUSTOMER360.RAW.CUSTOMERS (
  CUSTOMER_ID STRING NOT NULL,
  EXTERNAL_ID STRING,
  FULL_NAME STRING,
  EMAIL STRING,
  PHONE STRING,
  DATE_OF_BIRTH DATE,
  GENDER STRING,
  ADDRESS_LINE_1 STRING,
  ADDRESS_LINE_2 STRING,
  CITY STRING,
  STATE_PROVINCE STRING,
  POSTAL_CODE STRING,
  COUNTRY_CODE STRING,
  CUSTOMER_STATUS STRING,
  SOURCE_SYSTEM STRING,
  MARKETING_CONSENT BOOLEAN,
  SOURCE_PAYLOAD VARIANT,
  SOURCE_UPDATED_AT TIMESTAMP_TZ,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_CUSTOMERS PRIMARY KEY (CUSTOMER_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS CUSTOMER360.RAW.CUSTOMER_EVENTS (
  EVENT_ID STRING NOT NULL,
  SOURCE STRING NOT NULL,
  CUSTOMER_ID STRING,
  OCCURRED_AT TIMESTAMP_TZ NOT NULL,
  PAYLOAD VARIANT,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_CUSTOMER_EVENTS PRIMARY KEY (EVENT_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS CUSTOMER360.RAW.TRANSACTIONS (
  TRANSACTION_ID STRING NOT NULL,
  CUSTOMER_ID STRING NOT NULL,
  TRANSACTION_TYPE STRING,
  STATUS STRING,
  AMOUNT NUMBER(18,2) NOT NULL,
  TAX_AMOUNT NUMBER(18,2),
  DISCOUNT_AMOUNT NUMBER(18,2),
  CURRENCY STRING,
  PAYMENT_METHOD STRING,
  CHANNEL STRING,
  PRODUCT_ID STRING,
  QUANTITY NUMBER(10,0),
  TRANSACTED_AT TIMESTAMP_TZ NOT NULL,
  SOURCE_PAYLOAD VARIANT,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS CUSTOMER360.RAW.SUPPORT_INTERACTIONS (
  SUPPORT_ID STRING NOT NULL,
  CUSTOMER_ID STRING NOT NULL,
  TICKET_NUMBER STRING,
  CHANNEL STRING,
  CATEGORY STRING,
  PRIORITY STRING,
  STATUS STRING,
  SUBJECT STRING,
  SATISFACTION_SCORE NUMBER(1,0),
  OPENED_AT TIMESTAMP_TZ NOT NULL,
  FIRST_RESPONSE_AT TIMESTAMP_TZ,
  RESOLVED_AT TIMESTAMP_TZ,
  SOURCE_PAYLOAD VARIANT,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_SUPPORT PRIMARY KEY (SUPPORT_ID) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS CUSTOMER360.RAW.MARKETING_INTERACTIONS (
  MARKETING_ID STRING NOT NULL,
  CUSTOMER_ID STRING NOT NULL,
  CAMPAIGN_ID STRING NOT NULL,
  CAMPAIGN_NAME STRING,
  CHANNEL STRING,
  INTERACTION_TYPE STRING,
  CONVERSION_VALUE NUMBER(18,2),
  OCCURRED_AT TIMESTAMP_TZ NOT NULL,
  METADATA VARIANT,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_MARKETING PRIMARY KEY (MARKETING_ID) NOT ENFORCED
);
