CREATE TABLE IF NOT EXISTS CUSTOMER360.RAW.CUSTOMER_EVENTS (
  EVENT_ID STRING, SOURCE STRING, CUSTOMER_ID STRING, OCCURRED_AT TIMESTAMP_TZ, PAYLOAD VARIANT, INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
