-- Run with a role allowed to create warehouses and databases.
CREATE WAREHOUSE IF NOT EXISTS CUSTOMER360_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS CUSTOMER360;
CREATE SCHEMA IF NOT EXISTS CUSTOMER360.RAW WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS CUSTOMER360.ANALYTICS WITH MANAGED ACCESS;

USE WAREHOUSE CUSTOMER360_WH;
USE DATABASE CUSTOMER360;
