CREATE WAREHOUSE IF NOT EXISTS CUSTOMER360_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE DATABASE IF NOT EXISTS CUSTOMER360;
CREATE SCHEMA IF NOT EXISTS CUSTOMER360.RAW;
CREATE SCHEMA IF NOT EXISTS CUSTOMER360.ANALYTICS;
